export const data = [
  {
    id: 1,
    title: "Hogar",
    img: "https://retos-directivos.eae.es/wp-content/uploads/2020/12/admin-ajax-1.jpeg",
  },
  {
    id: 2,
    title: "Profesionales",
    img: "https://blog.posgrados.ibero.mx/wp-content/uploads/2021/09/Competencias-profesionales-scaled.jpeg",
  },
  {
    id: 3,
    title: "Tecnologia",
    img: "https://concepto.de/wp-content/uploads/2014/08/tecnologia-e1551386720574-800x412.jpg",
  },
  {
    id: 4,
    title: "Otros servicios",
    img: "https://www.asis-te.com/wp-content/uploads/2020/11/otros-servicios-1024x683.jpg",
  },
];

export const dataServices = [
  {
    id: 1,
    title: "Electricidad",
    service: "Colocación de Paneles solares",
    location: "Villa Mercedes, CABA",
    img: "https://d2jhl5pzkfi24b.cloudfront.net/article_image/0001/04/de9ccfa022c45ca2451976bc3ec43a75dcd75c51.jpeg",
    rating: 3.4,
  },
  {
    id: 2,
    title: "Carpintería",
    service: "Amueblamiento de cocina",
    location: "Palermo, CABA",
    img: "https://www.shutterstock.com/image-photo/carpenter-working-equipment-on-wooden-260nw-1886769229.jpg",
    rating: 5.0,
  },
  {
    id: 3,
    title: "Construcción",
    service: "Construcción de viviendas",
    location: "Villa Mercedes, San Luis",
    img: "https://gicaperu.com/wp-content/uploads/2018/06/contruccion-civil-geotecnia-gica-lima-peru-6.jpg",
    rating: 4.4,
  },
  {
    id: 4,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 5,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 6,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 7,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 8,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 9,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 10,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 11,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 12,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
  {
    id: 13,
    title: "Plomería",
    service: "Insumos",
    location: "Carlos Paz, Córdoba",
    img: "https://familiamultiservicios.com/wp-content/uploads/2016/06/service-1.jpg",
    rating: 2.4,
  },
];

export const subCategories = [
  "Electricidad",
  "Carpintería",
  "Gasista",
  "Plomería",
  "Construcción",
  "Service electrodomésticos",
];
